// Generated by Rullst.
pub mod m20260601000000_create_users_table;
pub mod m20260917000003_create_one_time_purchases;
pub mod m20260917000004_create_tester_certificates;
pub mod m20260917000005_add_live_commerce_controls;
pub mod m20260918000006_add_password_recovery;
pub mod m20260919000007_add_purchase_confirmation_mail;

pub fn get_migrations() -> Vec<Box<dyn rullst::db::schema::Migration>> {
    vec![
        Box::new(m20260601000000_create_users_table::MigrationImpl),
        Box::new(m20260917000003_create_one_time_purchases::MigrationImpl),
        Box::new(m20260917000004_create_tester_certificates::MigrationImpl),
        Box::new(m20260917000005_add_live_commerce_controls::MigrationImpl),
        Box::new(m20260918000006_add_password_recovery::MigrationImpl),
        Box::new(m20260919000007_add_purchase_confirmation_mail::MigrationImpl),
    ]
}
