// Generated by Rullst.
pub mod m20260601000000_create_users_table;
pub mod m20260917000003_create_one_time_purchases;

pub fn get_migrations() -> Vec<Box<dyn rullst::db::schema::Migration>> {
    vec![
        Box::new(m20260601000000_create_users_table::MigrationImpl),
        Box::new(m20260917000003_create_one_time_purchases::MigrationImpl),
    ]
}
