[package]
name = "omni-app"
version = "0.1.0"
authors = ["Rullst Developer"]
edition = "2021"

[dependencies]
dioxus = { version = "0.6", features = ["desktop"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

[package.metadata.cargo-machete]
ignored = ["async-trait", "rullst-core", "subtle", "serde", "axum", "serde_json", "tokio", "lettre", "opentelemetry", "opentelemetry-otlp", "opentelemetry_sdk", "redis", "rullst-connect", "rullst-macros", "toml", "tracing-opentelemetry", "urlencoding", "base64", "notify", "ring", "rullst-auth"]
